// GENERATED by tools/stamp-version.mjs — run it before committing.
// The hash covers every precached file, so any content change ships as a new
// service worker and the in-app update toast fires on installed devices.
export const APP_VERSION = '2026-08-18 · 5bdca756fe';
export const CACHE_VERSION = 'praxis-5bdca756fe';
export const BUILD_FILES = 35;
