// Generates data/brush.js — brush-mark path data for Praxis, produced by the
// EnsoKit brush engine so the motif matches the rest of the Enso design system.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';

const require = createRequire(import.meta.url);
const brush = require('../../ensokit/src/brush.js');
const { ensoPoints, strokePoints, dotPoints, toPathD } = brush;

const d = pts => toPathD(pts, 1);

// Logo ring — open ensō, thick shoulder, tapered tail.
const enso = d(ensoPoints('praxis-mark', { R: 33, w: 12, gap: 0.62, rot: -0.55, wob: 2.1 }));

// Section rules — horizontal brush sweeps on a 100 × 14 grid.
function sweep(seed, len = 96, y = 7) {
  const pts = [[2, y + 1.4], [len * 0.32, y - 1.1], [len * 0.66, y + 1.2], [len, y - 0.6]];
  return d(strokePoints(seed, pts, 5.2, { taper: 'both' }));
}
const rules = ['praxis-rule-a', 'praxis-rule-b', 'praxis-rule-c'].map((s, i) => sweep(s, 96 - i * 4));

// Ink dot for phase markers.
const dot = d(dotPoints('praxis-dot', 50, 50, 34));

// Brush check for completed items (two strokes merged into one path).
const check = [
  d(strokePoints('praxis-check-1', [[18, 52], [40, 74]], 11, { taper: 'none' })),
  d(strokePoints('praxis-check-2', [[38, 74], [84, 24]], 11, { taper: 'none' }))
].join(' ');

// Divider flourish for the top of long pages.
const flourish = d(strokePoints('praxis-flourish', [[6, 9], [30, 4], [58, 11], [94, 5]], 3.2, { taper: 'both' }));

const out = `// GENERATED by tools/make-brush.mjs — do not edit.
// Brush geometry from the EnsoKit engine (ensokit/src/brush.js).
export const ENSO = '${enso}';
export const RULES = ${JSON.stringify(rules)};
export const DOT = '${dot}';
export const CHECK = '${check}';
export const FLOURISH = '${flourish}';

const svg = (d, vb, extra = '') =>
  \`<svg viewBox="\${vb}" aria-hidden="true" focusable="false" preserveAspectRatio="none" \${extra}><path d="\${d}" fill="currentColor"/></svg>\`;

export const ensoMark = (cls = 'brush-mark') =>
  \`<svg class="\${cls}" viewBox="0 0 100 100" aria-hidden="true" focusable="false"><path d="\${ENSO}" fill="currentColor"/></svg>\`;
export const brushRule = (i = 0, cls = 'brush-rule') =>
  \`<span class="\${cls}">\${svg(RULES[i % RULES.length], '0 0 100 14')}</span>\`;
export const brushDot = (cls = 'brush-dot') =>
  \`<span class="\${cls}"><svg viewBox="0 0 100 100" aria-hidden="true" focusable="false"><path d="\${DOT}" fill="currentColor"/></svg></span>\`;
export const brushCheck = () =>
  \`<svg class="brush-check" viewBox="0 0 100 100" aria-hidden="true" focusable="false"><path d="\${CHECK}" fill="currentColor"/></svg>\`;
export const brushFlourish = () =>
  \`<span class="brush-flourish">\${svg(FLOURISH, '0 0 100 14')}</span>\`;
`;

writeFileSync(new URL('../data/brush.js', import.meta.url), out);
console.log('brush data written · enso path', enso.length, 'chars');
