// Stamps a content hash into sw.js and js/version.js.
//
// Why this exists: a browser only re-installs a service worker when sw.js itself
// changes byte-for-byte. Editing content files alone would leave every installed
// phone serving the old cached build forever, and the in-app update toast would
// never fire. Hashing the precached files into VERSION makes any content change
// produce a new sw.js, which is what triggers the update prompt.
//
// Run before every commit:  node tools/stamp-version.mjs
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const WATCH = ['index.html', 'manifest.webmanifest', 'css', 'js', 'data', 'icons'];
const SKIP = new Set(['js/version.js']);   // rewritten by this script

function walk(p, out = []) {
  const abs = join(ROOT, p);
  if (statSync(abs).isDirectory()) {
    for (const e of readdirSync(abs).sort()) walk(join(p, e), out);
  } else if (!SKIP.has(p) && !p.endsWith('.DS_Store')) {
    out.push(p);
  }
  return out;
}

const files = WATCH.flatMap(w => walk(w)).sort();
const h = createHash('sha256');
for (const f of files) {
  h.update(f);
  h.update(readFileSync(join(ROOT, f)));
}
const hash = h.digest('hex').slice(0, 10);
const date = new Date().toISOString().slice(0, 10);

// sw.js — cache name
const swPath = join(ROOT, 'sw.js');
let sw = readFileSync(swPath, 'utf8');
const swBefore = sw;
sw = sw.replace(/const VERSION = '[^']*';/, `const VERSION = 'praxis-${hash}';`);
if (sw === swBefore && !sw.includes(`praxis-${hash}`)) {
  console.error('could not find the VERSION line in sw.js');
  process.exit(1);
}
writeFileSync(swPath, sw);

// js/version.js — what the app displays
writeFileSync(join(ROOT, 'js/version.js'), `// GENERATED by tools/stamp-version.mjs — run it before committing.
// The hash covers every precached file, so any content change ships as a new
// service worker and the in-app update toast fires on installed devices.
export const APP_VERSION = '${date} · ${hash}';
export const CACHE_VERSION = 'praxis-${hash}';
export const BUILD_FILES = ${files.length};
`);

console.log(`stamped praxis-${hash} across ${files.length} files (${date})`);
console.log(files.map(f => '  ' + relative('.', f)).join('\n'));
